apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener:  myapp-github-ci-listener
  name: myapp-github-ci-listener
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-myapp-github-ci-listener
