apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: myapp-github-ci-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-listener
      bindings:
        - ref: myapp-ci-pipeline-binding
      template:
        ref: myapp-ci-trigger-pipeline-template