apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
data:
  ARGOCD_SERVER: openshift-gitops-server-openshift-gitops.apps.cluster-qrbn4.qrbn4.sandbox2884.opentlc.com
#  ARGOCD_SERVER: openshift-gitops-server-openshift-gitops.apps.skylake.demolab.local