apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
data:
  ARGOCD_AUTH_TOKEN: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKaGNtZHZZMlFpTENKemRXSWlPaUp3Y205cU9tMTVZWEJ3T20xNVlYQndMWE41Ym1NaUxDSnVZbVlpT2pFM05Ea3dORGN6T1RNc0ltbGhkQ0k2TVRjME9UQTBOek01TXl3aWFuUnBJam9pT1RsbFptTXlNV1V0WXpnNE9DMDBOemRoTFRrNE5qY3ROamxoWVRJd09HSTJPRFl3SW4wLnZjY1p3UnJTUDExUWwwT1NmWTMtUEROS2pxYWV5Znl2WlVPQy1GT01ldk0=