apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
data:
  ARGOCD_AUTH_TOKEN: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKaGNtZHZZMlFpTENKemRXSWlPaUp3Y205cU9tMTVZWEJ3T20xNVlYQndMWE41Ym1NaUxDSnVZbVlpT2pFM01qYzRNREV6T0RBc0ltbGhkQ0k2TVRjeU56Z3dNVE00TUN3aWFuUnBJam9pTldReFpXWmxNakV0TlRJeFlTMDBObVpoTFRneVlqUXROREUyWkRkbU0yRmhNRGMxSW4wLmdLT1RHWG1LOHJlMEFBTFdVSFl3a0hUQmlSakFJdnNHY3FIMWI1dDkyQTg=