apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
data:
#  ARGOCD_SERVER: openshift-gitops-server-openshift-gitops.apps.cluster-fchs4.fchs4.sandbox2970.opentlc.com
  ARGOCD_SERVER: openshift-gitops-server-openshift-gitops.apps.conroe.demolab.local
