apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
data:
  ARGOCD_AUTH_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJwcm9qOm15YXBwOm15YXBwLXN5bmMiLCJuYmYiOjE2OTkyODc5NTUsImlhdCI6MTY5OTI4Nzk1NSwianRpIjoiNzQxYjdlNGUtNjcyYy00ZDg0LTlmZmYtNWE1ZWIzODI4ZTIxIn0.5nQJBcsI7rs5jA6FADLF1ON-qjzZ7rxSYca3xWFrm1Y