apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
data:
  ARGOCD_AUTH_TOKEN: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKaGNtZHZZMlFpTENKemRXSWlPaUp3Y205cU9tMTVZWEJ3T20xNVlYQndMWE41Ym1NaUxDSnVZbVlpT2pFMk9USTNNVFV5TVRJc0ltbGhkQ0k2TVRZNU1qY3hOVEl4TWl3aWFuUnBJam9pTWpBeE1USXpZekl0TkRoak9DMDBZV0ZoTFdKaU9UUXROemt3WWpBNU5XTXhZVFV5SW4wLklDeFVacG9DTDJUb0pjYlJmdV9vVVJnV2cyNWF5cVQ0a2pwV3NUbF8xRVU=