kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: cli
  namespace: myapp-ci
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:878b31040c88f3eb56ca2bd2d77fa29128dad732850dd3fe779037ec9643bf02'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source