apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: myapp-runtime
spec:
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/myapp-ci/myapp-runtime
  type: image 