apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  params:
    - name: TLSVERIFY
      description: Verify the TLS on the registry endpoint
      type: string
      default: 'false'
    - name: STORAGE_DRIVER
      description: The Buildah storage STORAGE_DRIVER.
      type: string
    - name: intermediate-image
      type: string
    - name: path
      type: string
  workspaces:
    - name: files
  steps:
    - name: ls-1
      command:
        - ls
        - -al
        - /$(workspaces.files.path)
      image: image-registry.openshift-image-registry.svc:5000/myapp-ci/buildah:latest
    - name: ls-2
      command:
        - ls
        - -al
        - /$(workspaces.files.path)/$(params.path)
      image: image-registry.openshift-image-registry.svc:5000/myapp-ci/buildah:latest
    - name: cat-dockerfile
      command:
        - cat
        - /$(workspaces.files.path)/$(params.path)/dockerfile/build-src-dockerfile
      image: image-registry.openshift-image-registry.svc:5000/myapp-ci/buildah:latest
    - name: ls-docker-content-1
      command:
        - ls 
        - -al
      image: image-registry.openshift-image-registry.svc:5000/myapp-ci/buildah:latest
      workingDir: /$(workspaces.files.path)/$(params.path)
    - name: ls-docker-content-2
      command:
        - ls 
        - -al
        - src/main/liberty/config/server.xml
      image: image-registry.openshift-image-registry.svc:5000/myapp-ci/buildah:latest
      workingDir: /$(workspaces.files.path)/$(params.path)
    - name: build
      command:
        - buildah
        - bud
        - '--tls-verify=$(params.TLSVERIFY)'
        - '--storage-driver=$(params.STORAGE_DRIVER)'
        - '--root'
        - '/$(workspaces.files.path)/buildah-containers'
        - '--layers'
        - '-f'
        - /$(workspaces.files.path)/$(params.path)/dockerfile/build-src-dockerfile
        - '-t'
        - $(params.intermediate-image)
        - .
      image: image-registry.openshift-image-registry.svc:5000/myapp-ci/buildah:latest
      securityContext:
        capabilities:
          add: ["SETFCAP"]
      workingDir: /$(workspaces.files.path)/$(params.path)
      resources: {}
  
