apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  params:
    - name: TLSVERIFY
      description: Verify the TLS on the registry endpoint
      type: string
      default: 'false'
    - name: STORAGE_DRIVER
      description: The Buildah storage STORAGE_DRIVER.
      type: string
  resources:
    outputs:
      - name: intermediate-image
        type: image
  steps:
    - name: build
      command:
        - buildah
        - bud
        - '--tls-verify=$(params.TLSVERIFY)'
        - '--storage-driver=$(params.STORAGE_DRIVER)'
        - '--root'
        - '/files/buildah-containers'
        - '--layers'
        - '-f'
        - /files/source/dockerfile/build-src-dockerfile
        - '-t'
        - $(resources.outputs.intermediate-image.url)
        - .
      image: image-registry.openshift-image-registry.svc:5000/myapp-ci/buildah:latest
# Changes for skylake
      securityContext:
        capabilities:
          add: ["SETFCAP"]
      workingDir: /files/source
      resources: {}
  workspaces:
  - name: files
    mountPath: /files
