apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: configure-kustomization-file
spec:
  params:
  - name: image-url
    type: string
  steps:  
    - name: configure-kustomization-file
      script: >-
        #!/usr/bin/env bash

        set +x

        ls -al

        kustomize edit set image $(params.image-url)

        ls -al

        cat kustomization.yaml

      image: quay.io/marrober/kustomize:latest
      workingDir: /files/myapp-cd/env/overlays/01-dev     
  workspaces:
  - name: files
    mountPath: /files   