apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  annotations:
    tekton.dev/categories: Git
    tekton.dev/tags: git
    tekton.dev/displayName: "git clone"
spec:
  workspaces:
    - name: output
      description: Target workspace for the git repository.
  params:
    - name: url
      description: Repository URL to clone from.
      type: string
    - name: revision
      description: Revision to checkout. (branch, tag, sha, ref, etc...)
      type: string
      default: ""
    - name: source-clone-target-path
      type: string
    - name: repoName
      type: string
    - name: verbose
      description: Log level.
      type: string
      default: "true"
    - name: image
      description: The image providing the git-init binary that this Task runs.
      type: string
      default: "image-registry.openshift-image-registry.svc:5000/myapp-ci/git-init-rhel9:v1.19.2"
  results:
    - name: commit
      description: The precise commit SHA that was fetched by this Task.
    - name: url
      description: The precise URL that was fetched by this Task.
    - name: committer-date
      description: The epoch timestamp of the commit that was fetched by this Task.
  steps:
    - name: clone
      image: "$(params.image)"
      env:
      - name: PARAM_VERBOSE
        value: $(params.verbose)
      - name: WORKSPACE_OUTPUT_PATH
        value: $(workspaces.output.path)
      - name: PARAM_URL
        value: $(params.url)
      - name: PARAM_REVISION
        value: $(params.revision)
      script: |
        #!/usr/bin/env sh
        set -eu

        if [ "${PARAM_VERBOSE}" = "true" ] ; then
          set -x
        fi

        cd ${WORKSPACE_OUTPUT_PATH}

        mkdir $(params.source-clone-target-path)

        cd $(params.source-clone-target-path)

        pwd

        git clone ${PARAM_URL} 

        ls -alR

        cd ${WORKSPACE_OUTPUT_PATH}/$(params.source-clone-target-path)/$(params.repoName)

        ls -alR

        git checkout ${PARAM_REVISION}

        ls -al 

        RESULT_SHA="$(git rev-parse HEAD)"
        EXIT_CODE="$?"
        if [ "${EXIT_CODE}" != 0 ] ; then
          exit "${EXIT_CODE}"
        fi
        RESULT_COMMITTER_DATE="$(git log -1 --pretty=%ct)"
        printf "%s" "${RESULT_COMMITTER_DATE}" > "$(results.committer-date.path)"
        printf "%s" "${RESULT_SHA}" > "$(results.commit.path)"
        printf "%s" "${PARAM_URL}" > "$(results.url.path)"