apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: set-commit-status
spec:
  params:
  - name: GIT_REPO
    type: string
  - name: REPO
    type: string
  - default: git-host-access-token
    name: GIT_TOKEN_SECRET_NAME
    type: string
  - default: token
    name: GIT_TOKEN_SECRET_KEY
    type: string
  - name: COMMIT_SHA
    type: string
  - name: DESCRIPTION
    type: string
  - name: CONTEXT
    type: string
  - name: STATE
    type: string
  steps:
  - name: show-params
    script: >-
      #!/bin/sh

      echo "Git_REPO : " $(params.GIT_REPO)

      echo "REPO : " $(params.REPO)

      echo "GIT_TOKEN_SECRET_NAME : " $(params.GIT_TOKEN_SECRET_NAME)

      echo "GIT_TOKEN_SECRET_KEY : " $(params.GIT_TOKEN_SECRET_KEY)

      echo "COMMIT_SHA : " $(params.COMMIT_SHA)

      echo "DESCRIPTION : " $(params.DESCRIPTION)

      echo "CONTEXT : " $(params.CONTEXT)

      echo "STATE : " $(params.STATE)

    image: image-registry.openshift-image-registry.svc:5000/myapp-ci/gitops-commit-status:latest
  - name: set-commit-status
    env:
    - name: GITHOSTACCESSTOKEN
      valueFrom:
        secretKeyRef:
          key: $(params.GIT_TOKEN_SECRET_KEY)
          name: $(params.GIT_TOKEN_SECRET_NAME)
    image: image-registry.openshift-image-registry.svc:5000/myapp-ci/ubi:latest
    resources: {}
    script: >
      #!/bin/sh

      curl -s -H 'Content-Type: application/json' -X POST -u $GITHOSTACCESSTOKEN:x-oauth-basic -d '{"state":"$(params.STATE)", "description":"$(params.DESCRIPTION)", "context":"$(params.CONTEXT)"}' https://api.github.com/repos/$(params.GIT_REPO)/statuses/$(params.COMMIT_SHA) > curl-cmd.sh


      cat curl-cmd.sh

      chmod u+x curl-cmd.sh

      sh ./curl-cmd.sh

      echo "completed"
