apiVersion: apps/v1
kind: Deployment
metadata:
  name: smee-production-build
  labels:
    app.kubernetes.io/part-of: smee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gosmee
  template:
    metadata:
      labels:
        app: gosmee
    spec:
      containers:
        - image: default-route-openshift-image-registry.apps.cluster-84m6f-1.sandbox851.opentlc.com/gosmee:latest
          imagePullPolicy: IfNotPresent
          name: gosmee
          args:
            [
              "client",
              "--saveDir",
              "/tmp/save",
              "https://smee.io/6mz30aVAA29kWkE",
              "http://myapp-github-ci-prod-listener-myapp-ci.apps.cluster-84m6f-1.sandbox851.opentlc.com",
            ]
