apiVersion: apps/v1
kind: Deployment
metadata:
  name: smee-main-build
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gosmee
  template:
    metadata:
      labels:
        app: gosmee
    spec:
      containers:
        - image: ghcr.io/chmouel/gosmee:latest
          imagePullPolicy: IfNotPresent
          name: gosmee
          args:
            [
              "client",
              "--saveDir",
              "/tmp/save",
              "https://smee.io/3aC3MfW0AoBzRW6",
              "http://myapp-github-ci-listener-myapp-ci.apps.celeron.demolab.local/",
            ]
